version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
    image: ghcr.io/soroushshirali/party-equipments-shop:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production